# Generated by Django 2.2.6 on 2019-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='consultant_number',
            field=models.IntegerField(default=0),
        ),
    ]
