# Generated by Django 2.2.6 on 2019-10-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_register_consultant_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
