# Generated by Django 2.2.6 on 2019-11-01 15:23

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0002_remove_user_consultant_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=None, primary_key=True,
                                                     serialize=False),
            preserve_default=False,
        ),
    ]
