# Generated by Django 2.2.6 on 2019-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191026_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
